In [1]:
import pandas as pd
from google.colab import drive

import io

In [10]:
# URL of the dataset
url = 'https://opendata-ajuntament.barcelona.cat/resources/bcn/EstadisticaPadro/pad/2023/2023_pad_mdb_nacionalitat-contintent_edat-q_sexe.csv'

# Read the data into a DataFrame
df_poblacio = pd.read_csv(url)
df_poblacio.drop(columns=['Codi_Districte', 'Codi_Barri', 'Data_Referencia'], inplace=True)

# URL of the dataset
url = 'https://opendata-ajuntament.barcelona.cat/resources/bcn/EstadisticaPadro/dimensions/pad_dimensions.csv'

# Read the data into a DataFrame
df_dimensions = pd.read_csv(url)

In [11]:
df_dimensions

,Codi_Dimensio,Desc_Dimensio,Codi_Valor,Desc_Valor_CA,Desc_Valor_ES,Desc_Valor_EN
0,1,SEXE,1,Dona,Mujer,Female
1,1,SEXE,2,Home,Hombre,Male
2,2,EDAT_1,0,0 anys,0 años,0 years
3,2,EDAT_1,1,1 anys,1 años,1 years
4,2,EDAT_1,2,2 anys,2 años,2 years
...,...,...,...,...,...,...
1492,38,NACIONALITAT_DEST,141,República Democràtica del Congo,República Democrática del Congo,DR Congo
1493,38,NACIONALITAT_DEST,143,"Iraq, l'",Iraq,Iraq
1494,38,NACIONALITAT_DEST,144,Kenya,Kenia,Kenya
1495,38,NACIONALITAT_DEST,145,Seychelles,Seychelles,Seychelles
1496,38,NACIONALITAT_DEST,999,No consta,No consta,Not available

In [12]:
# Decode df_poblacio with df_dimensions
for dimension in ['NACIONALITAT_CONTINENT', 'EDAT_Q', 'SEXE']:
    # Filter df_dimensions for the current dimension
    df_dim_filter = df_dimensions[df_dimensions['Desc_Dimensio'] == dimension]

    # Merge with df_poblacio on the code column
    df_poblacio = pd.merge(df_poblacio, df_dim_filter, left_on=dimension, right_on='Codi_Valor', how='left')

    # Replace the code with the description
    df_poblacio[dimension] = df_poblacio['Desc_Valor_EN']

    # Drop extra columns from the merge
    df_poblacio.drop(['Codi_Dimensio', 'Desc_Dimensio', 'Codi_Valor', 'Desc_Valor_CA', 'Desc_Valor_ES', 'Desc_Valor_EN'], axis=1, inplace=True)

print(df_poblacio)

      Nom_Districte            Nom_Barri Valor NACIONALITAT_CONTINENT  \
0      Ciutat Vella             el Raval    46                 Africa
1      Ciutat Vella             el Raval    49                 Africa
2      Ciutat Vella             el Raval    30                 Africa
3      Ciutat Vella             el Raval    34                 Africa
4      Ciutat Vella             el Raval    14                 Africa
...             ...                  ...   ...                    ...
10637    Sant Martí  la Verneda i la Pau    ..                Oceania
10638    Sant Martí  la Verneda i la Pau    ..                Oceania
10639    Sant Martí  la Verneda i la Pau    ..                Oceania
10640    Sant Martí  la Verneda i la Pau    ..          Not available
10641    Sant Martí  la Verneda i la Pau    ..          Not available

            EDAT_Q    SEXE
0         <5 years  Female
1         <5 years    Male
2        5-9 years  Female
3        5-9 years    Male
4      10-14 years  Female
...            ...     ...
10637  30-34 years  Female
10638  30-34 years    Male
10639  35-39 years    Male
10640  35-39 years  Female
10641  50-54 years    Male

[10642 rows x 6 columns]

In [ ]:
df_poblacio.to_csv('/content/drive/MyDrive/ML_Project/poblacio_barcelona.csv')

# Renda

In [6]:
# URL of the dataset
url = "https://opendata-ajuntament.barcelona.cat/data/dataset/b5e41317-c66f-477f-a5f3-083554a6af71/resource/ad6de9c3-85e0-4ef4-9b3a-ab92a41ffef5/download/2021_atles_renda_p8020_distribucio.csv"

# Read the data into a DataFrame
df_renda = pd.read_csv(url)
df_renda.drop(columns=['Any','Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Seccio_Censal'], inplace=True)
df_renda

                                         Nom_Barri  Distribucio_P80_20
0                                         el Raval                 3.6
1                                         el Raval                 2.9
2                                         el Raval                 3.4
3                                         el Raval                 3.0
4                                         el Raval                 3.0
...                                            ...                 ...
1063                           la Verneda i la Pau                 2.4
1064                                       el Clot                 2.3
1065  Diagonal Mar i el Front Marítim del Poblenou                 2.9
1066  Diagonal Mar i el Front Marítim del Poblenou                 2.3
1067                       Provençals del Poblenou                 2.4

[1068 rows x 2 columns]

In [7]:
df_renda.to_csv('/content/drive/MyDrive/ML_Project/CSV/opendata_CSV/renda_barcelona.csv')

# Educació

In [13]:
# URL of the dataset
url = "https://opendata-ajuntament.barcelona.cat/data/dataset/b8267536-0b2b-49be-bfe8-6f4cb3bd9ddb/resource/0cbaed7d-cbd2-4868-b806-a42831529a05/download"

# Read the data into a DataFrame
df_educacio = pd.read_csv(url)
df_educacio.drop(columns=['Data_Referencia','Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'AEB', 'Seccio_Censal','SEXE'], inplace=True)
df_educacio

                 Nom_Barri Valor  NIV_EDUCA_esta
0                 el Raval     8               1
1                 el Raval    ..               1
2                 el Raval   103               2
3                 el Raval   118               2
4                 el Raval   103               3
...                    ...   ...             ...
12682  la Verneda i la Pau   196               4
12683  la Verneda i la Pau   147               5
12684  la Verneda i la Pau   109               5
12685  la Verneda i la Pau    18               6
12686  la Verneda i la Pau    13               6

[12687 rows x 3 columns]

In [14]:
# Decode df_educacio with df_dimensions
for dimension in ['NIV_EDUCA_esta']:
    # Filter df_dimensions for the current dimension
    df_dim_filter = df_dimensions[df_dimensions['Desc_Dimensio'] == dimension]

    # Merge with df_educacio on the code column
    df_educacio = pd.merge(df_educacio, df_dim_filter, left_on=dimension, right_on='Codi_Valor', how='left')

    # Replace the code with the description
    df_educacio[dimension] = df_educacio['Desc_Valor_EN']

    # Drop extra columns from the merge
    df_educacio.drop(['Codi_Dimensio', 'Desc_Dimensio', 'Codi_Valor', 'Desc_Valor_CA', 'Desc_Valor_ES', 'Desc_Valor_EN'], axis=1, inplace=True)

print(df_educacio)

                 Nom_Barri Valor  \
0                 el Raval     8
1                 el Raval    ..
2                 el Raval   103
3                 el Raval   118
4                 el Raval   103
...                    ...   ...
12682  la Verneda i la Pau   196
12683  la Verneda i la Pau   147
12684  la Verneda i la Pau   109
12685  la Verneda i la Pau    18
12686  la Verneda i la Pau    13

                                          NIV_EDUCA_esta
0                            Less than primary education
1                            Less than primary education
2                                      Primary education
3                                      Primary education
4                              Lower secondary education
...                                                  ...
12682  Upper secondary or post-secondary non-tertiary...
12683                                 Tertiary education
12684                                 Tertiary education
12685                                      Not available
12686                                      Not available

[12687 rows x 3 columns]

In [15]:
df_educacio.to_csv('/content/drive/MyDrive/ML_Project/CSV/opendata_CSV/educacio_barcelona.csv')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive